name: Collect VPN Configurations

on:
  schedule:
    - cron: '0 */6 * * *'  # هر 6 ساعت
  workflow_dispatch:  # امکان اجرای دستی
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  collect-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}  # استفاده از توکن جدید

      - name: List repository contents
        run: ls -la  # برای دیباگ: نمایش فایل‌های مخزن

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 dnspython geoip2 gitpython schedule wget jdatetime

      - name: Run collector script
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}  # توکن برای اسکریپت
        run: python config_collector.py

      - name: Commit and push changes
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}  # توکن برای push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Update configs $(date)" || echo "No changes to commit"
          git remote set-url origin https://x:${REPO_TOKEN}@github.com/PlanAsli/Beta.git
          git push origin main
