name: Collect VPN Configurations

on:
  schedule:
    - cron: '0 */6 * * *'  # هر 6 ساعت
  workflow_dispatch:  # امکان اجرای دستی

jobs:
  collect-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 dnspython geoip2 gitpython schedule wget

      - name: Run collector script
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}  # توکن از سیکرت‌ها
        run: python config_collector.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Update configs $(date)"
          git push
